config/routes.rb
Rails.application.routes.draw do
  resources :links
  resources :users
  root to: 'links#index'
end

app/models/link.rb
class Link < ActiveRecord::Base
  acts_as_taggable # Alias for acts_as_taggable_on :tags
  acts_as_taggable_on :links
end

app/models/user.rb
class User < ActiveRecord::Base
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
 
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  http_basic_authenticate_with :name => APP_CONFIG[:name], :password => APP_CONFIG[:password], :except => :index

  

  before_action :set_link, only: [:show, :edit, :update, :destroy]

  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:icon, :url, :urltext, :description, :tag, :name, :tag_list)
    end

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:password, :name, :email)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
	def index
		@users = User.all
	end

    def index
    	@links = Link.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/links_helper.rb
module LinksHelper
	def sortable(column, title = nil)
  		title ||= column.titleize
  		css_class = column == sort_column ? "current #{sort_direction}" : nil
  		direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
  		link_to title, {:sort => column, :direction => direction}, {:class => css_class}
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Making A Ruckus', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Makingaruckus'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Makingaruckus'}"
    == stylesheet_link_tag "application", :media => 'all'
    == javascript_include_tag 'application'
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield

app/views/links/_form.html.slim
= simple_form_for(@link) do |f|
  = f.error_notification

  .form-inputs
    = f.input :icon
    = f.input :url
    = f.input :urltext
    = f.input :description
    = f.input :tag

  .form-actions
    = f.button :submit

app/views/links/edit.html.slim
h1 Editing link

== render 'form'

= link_to 'Show', @link
'|
= link_to 'Back', links_path

app/views/links/index.html.slim
<div class="container">


div class="col-md-12 divide"
h1 Ruckus Library
div class="toc col-md-4"
  <ul>
    <li class="glyphicon glyphicon-globe"> Web Page / Article
    <li class="glyphicon glyphicon-book"> PDF / Book
    <li class="glyphicon glyphicon-film"> Video
    <li class="glyphicon glyphicon-search"> Search Results
  </ul>



table class=["table table-striped"]
  thead
    tr
      th Icon
      th Link
      th Description
      th Tag
      

  tbody 
    - @links.each do |link|
      tr
        - case link.icon
          - when "1"
            td class=["glyphicon glyphicon-globe"]
          - when "2"
            td class=["glyphicon glyphicon-book"] 
          - when "3"
            td class=["glyphicon glyphicon-film"]
          - when "4"
            td class=["glyphicon glyphicon-search"]
        td = link_to link.urltext, link.url
        td = link.description
        td = link.tag 
        // td = link_to 'Show', link
        // td = link_to 'Edit', edit_link_path(link), class: "btn btn-default"
        // td = link_to 'Destroy', link, data: {:confirm => 'Are you sure?'}, :method => :delete


= link_to 'New Link', new_link_path, class: "btn btn-default"

</div>

app/views/links/new.html.slim
h1 New link

== render 'form'

= link_to 'Back', links_path

app/views/links/show.html.slim
p#notice = notice

p
  strong Icon:
  = @link.icon
p
  strong Url:
  = @link.url
p
  strong Urltext:
  = @link.urltext
p
  strong Description:
  = @link.description

p
  strong Description:
  = @link.tag

= link_to 'Edit', edit_link_path(@link)
'|
= link_to 'Back', links_path

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/users/_form.html.slim
= simple_form_for(@user) do |f|
  = f.error_notification

  .form-inputs
    = f.input :password
    = f.input :name
    = f.input :email

  .form-actions
    = f.button :submit

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

= link_to 'Show', @user
'|
= link_to 'Back', users_path

app/views/users/index.html.slim
h1 Listing users

table
  thead
    tr
      th Password
      th Name
      th Email
      th
      th
      th

  tbody
    - @users.each do |user|
      tr
        td = user.password
        td = user.name
        td = user.email
        td = link_to 'Show', user
        td = link_to 'Edit', edit_user_path(user)
        td = link_to 'Destroy', user, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New User', new_user_path

app/views/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', users_path

app/views/users/show.html.slim
p#notice = notice

p
  strong Password:
  = @user.password
p
  strong Name:
  = @user.name
p
  strong Email:
  = @user.email

= link_to 'Edit', edit_user_path(@user)
'|
= link_to 'Back', users_path

app/views/visitors/index.html.slim
== render 'links/table'